### ISSUE TITLE
Depracated  MethodDescriptor.create

### ISSUE THREAD

**Issue by Citrullin** [btlines/grpcakkastream#10]
Got the following error for the generated code:
```
method create in object MethodDescriptor is deprecated: see corresponding Javadoc for more information.
[error]     MethodDescriptor.create(
```

I removed the compiler options to ignore the warnings.

**Comment by btlines** [comment]
Indeed, this is now replaced with `MethodDescriptor.newBuilder()`.

PR should follow shortly.

**Comment by btlines** [comment]
Solved with https://github.com/btlines/grpcakkastream/pull/11
