### ISSUE TITLE
Publish for multiple scala versions

### ISSUE THREAD

**Issue by sammerry** [btlines/grpcakkastream#2]
It would be great to publish this for multiple scala versions. Some of the newer compiler plugins like zinc aren't compatible with 2.10

**Comment by sammerry** [comment]
This may already be resolved in release 0.0.3 which has a published jar for the latest sbt 1.0.3 and scala 2.12.4

**Comment by btlines** [comment]
the `generator` lib is now published for both Scala 2.12 and 2.10 (and the `runtime` supports 2.12 and 2.11).
Is it enough to fix this issue ?
