### ISSUE TITLE
No version for sbt 1.0

### ISSUE THREAD

**Issue by pshirshov** [btlines/grpcakkastream#6]
It would be good to have this plugin published for 1.0

Please find P/R here: https://github.com/btlines/grpcakkastream/pull/7

For those who are interested in this I've published 1.0 version into bintray repo: https://dl.bintray.com/7mind/maven/beyondthelines/

sbt resolver to use: `resolvers += Resolver.bintrayRepo("7mind", "maven")`

Notes:

- I've updated plugin according to the latest changes in trueaccord stuff. Plugin seems to be working under 1.0, I can compile proto files into akka stubs. Though I'm not completely sure if everything is correct as per there are no tests available.

**Comment by pshirshov** [comment]
For those who are interested in this I've published 1.0 version into bintray repo: https://dl.bintray.com/7mind/maven/beyondthelines/

sbt resolver to use: `resolvers += Resolver.bintrayRepo("7mind", "maven")`

**Comment by btlines** [comment]
Solved with https://github.com/btlines/grpcakkastream/pull/7
